version: "3.7"
services:
  secrets:
    image: vault:1.3.2
    container_name: newVault
    volumes:
      - secrets:/etc/dotenv

  application:
    image: smarman/portfolio:0.0.2
    container_name: newApp
    volumes:
      - secrets:/etc/dotenv

volumes:
  secrets:
